// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/jason0x43/go-alfred"
	"google.golang.org/api/option"
	"toggl_time_entry_manipulator/estimation_client"
	"toggl_time_entry_manipulator/repository"
	cache2 "toggl_time_entry_manipulator/repository/cache"
)

// Injectors from wire.go:

func initializeRepository(workflow alfred.Workflow, serviceAccount option.ClientOption) (*cache2.CachedRepository, error) {
	cacheCacheFile := NewCacheFile(workflow)
	cacheCache, err := NewCache(cacheCacheFile)
	if err != nil {
		return nil, err
	}
	repositoryConfigFile := NewConfigFile(workflow)
	repositoryConfig, err := NewConfig(repositoryConfigFile)
	if err != nil {
		return nil, err
	}
	togglApiKey := repositoryConfig.TogglAPIKey
	togglClient := estimation_client.NewTogglClient(togglApiKey)
	estimationClient, err := estimation_client.NewEstimationClient(serviceAccount)
	if err != nil {
		return nil, err
	}
	timeEntryRepository := repository.NewTimeEntryRepository(repositoryConfig, togglClient, estimationClient)
	cachedRepository := cache2.NewCachedRepository(cacheCache, cacheCacheFile, timeEntryRepository)
	return cachedRepository, nil
}
