// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/jason0x43/go-alfred"
	"google.golang.org/api/option"
	"toggl_time_entry_manipulator/estimation_client"
	"toggl_time_entry_manipulator/repository"
	"toggl_time_entry_manipulator/repository/cache"
)

// Injectors from wire.go:

func initializeRepository(workflow alfred.Workflow, serviceAccount option.ClientOption) (*cache.CachedRepository, error) {
	cacheFile := NewCacheFile(workflow)
	cacheCache, err := NewCache(cacheFile)
	if err != nil {
		return nil, err
	}
	configFile := NewConfigFile(workflow)
	config, err := NewConfig(configFile)
	if err != nil {
		return nil, err
	}
	togglApiKey := config.TogglAPIKey
	togglClient := estimation_client.NewTogglClient(togglApiKey)
	estimationClient, err := estimation_client.NewEstimationClient(serviceAccount)
	if err != nil {
		return nil, err
	}
	timeEntryRepository := repository.NewTimeEntryRepository(config, togglClient, estimationClient)
	cachedRepository := cache.NewCachedRepository(cacheCache, timeEntryRepository)
	return cachedRepository, nil
}
