// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/jason0x43/go-alfred"
	"toggl_time_entry_manipulator/client"
	"toggl_time_entry_manipulator/command/add"
	"toggl_time_entry_manipulator/command/continue_entry"
	delete2 "toggl_time_entry_manipulator/command/delete"
	"toggl_time_entry_manipulator/command/get"
	"toggl_time_entry_manipulator/command/list"
	"toggl_time_entry_manipulator/command/modify"
	"toggl_time_entry_manipulator/command/stop"
	"toggl_time_entry_manipulator/repository"
)

// Injectors from wire.go:

func initializeCommands(workflow alfred.Workflow, firstCall bool) ([]alfred.Command, error) {
	cacheFile := NewCacheFile(workflow)
	iCache, err := NewCache(cacheFile)
	if err != nil {
		return nil, err
	}
	configFile := NewConfigFile(workflow)
	config, err := NewConfig(configFile)
	if err != nil {
		return nil, err
	}
	togglConfig := config.TogglConfig
	iTogglClient := client.NewTogglClient(togglConfig)
	clientOption, err := NewServiceAccount(workflow)
	if err != nil {
		return nil, err
	}
	firestoreConfig := config.FirestoreConfig
	iEstimationClient, err := client.NewEstimationClient(clientOption, firestoreConfig)
	if err != nil {
		return nil, err
	}
	iTimeEntryRepository := repository.NewTimeEntryRepository(iTogglClient, iEstimationClient)
	iCachedRepository := repository.NewCachedRepository(iCache, iTimeEntryRepository)
	workflowConfig := config.WorkflowConfig
	addEntryCommand := add.NewAddEntryCommand(iCachedRepository, workflowConfig)
	listEntryCommand := list.NewListEntryCommand(iCachedRepository, workflowConfig)
	getEntryCommand := get.NewGetEntryCommand(iCachedRepository)
	modifyEntryCommand := modify.NewModifyEntryCommand(iCachedRepository, workflowConfig)
	stopEntryCommand := stop.NewStopEntryCommand(iCachedRepository)
	deleteEntryCommand := delete2.NewDeleteEntryCommand(iCachedRepository)
	continueEntryCommand := continue_entry.NewContinueEntryCommand(iCachedRepository)
	v := NewCommands(firstCall, addEntryCommand, listEntryCommand, getEntryCommand, modifyEntryCommand, stopEntryCommand, deleteEntryCommand, continueEntryCommand)
	return v, nil
}
